name: ci
run-name: CI Run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          # Keep in sync with pyproject.toml
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install --with dev
      - name: Typecheck
        run: tasks/typecheck
      - name: Run tests
        run: tasks/test